# drift test — should be overwritten by the next sync from TokenVisor
apiVersion: v2
name: tokenvisor
description: TokenVisor Helm chart (operators required as pre-requisites)
type: application
version: 0.1.0
appVersion: "0.0.0"
dependencies:
  - name: victoria-logs-single
    version: 0.11.19
    repository: https://victoriametrics.github.io/helm-charts/
    condition: victoria-logs-single.enabled
