---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emu
  namespace: tokenvisor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: emu-sky-role
  namespace: tokenvisor
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emu-sky-cluster-role
  namespace: tokenvisor
  labels:
    parent: skypilot
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: emu-role-binding
  namespace: tokenvisor
subjects:
  - kind: ServiceAccount
    name: emu
    namespace: tokenvisor
roleRef:
  kind: Role
  name: emu-sky-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: emu-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: emu
    namespace: tokenvisor
roleRef:
  kind: ClusterRole
  name: emu-sky-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: studio
  namespace: tokenvisor
---
