---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server-pvc
  namespace: nfs-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-three-replica
  # storageClassName: local-path # For Single-Node Deployment
  resources:
    requests:
      storage: 500Gi # Adjust accordingly
---
