---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  # Parameters are commented out to prevent dynamic provisioning.
  # This StorageClass serves only as a grouping mechanism for the Static PVs.
  # Uncomment if dynamic provisioning is required.
  # server: nfs-server.nfs-server.svc.cluster.local
  # share: /
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nconnect=8
  - nfsvers=4.1
  - noatime
