apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-model-storage-pvc
spec:
  storageClassName: ""
  volumeName: seaweedfs-skypilot-amd-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
