apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-skypilot-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: seaweedfs-skypilot-pv-id
    volumeAttributes:
      collection: default
      replication: "000"
      path: /shared_hf_repo
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  mountOptions:
    - "dirAutoCreate=true"
    # this is to make the directory rwx for anyone
    - "umask=000"
